version: '3.8'

services:
  recommendation-engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - NODE_ENV=production
      - PORT=8003
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - MODEL_CACHE_DIR=/app/models/cache
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    depends_on:
      - chromadb
    restart: unless-stopped
    networks:
      - recommendation-network

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
    restart: unless-stopped
    networks:
      - recommendation-network

volumes:
  chroma_data:
    driver: local

networks:
  recommendation-network:
    driver: bridge